import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavMenu from './NavMenu';
import AuthProvider from './AuthProvider';
import  styles  from "./nav-menu.module.css"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AuthProvider>
    <html lang="en" className={styles.app}>
      <div>
        <NavMenu/>
        <body>{children}</body>
      </div>
    </html>
    </AuthProvider>
  )
}
